version: '3.8'

services:
  # Next.js Application
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./prisma/dev.db
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-key-here-change-this-in-production
    volumes:
      - ./prisma:/app/prisma
      - ./public/uploads:/app/public/uploads
    restart: unless-stopped

  # PostgreSQL Database (Alternative to SQLite)
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=cbds_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:


